name: Install PHP
description: Installs PHP on given version, defaults to PHP7.4
inputs:
  php-version:
    description: PHP version to install
    required: false
    default: 7.4
    type: string
  composer-version:
    description: Composer version to install
    required: false
    default: 1
    type: string

runs:
  using: composite
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl
          tools: composer:v${{ inputs.composer-version }}
          coverage: none