name: Install PHP
on: 
  workflow_call:
    inputs:
      php-version:
        description: PHP version to install
        required: false
        default: 7.4
        type: string
      composer-version:
        description: Composer version to install
        required: false
        default: 1
        type: string

jobs:
  install-php:
    runs-on: ubuntu-latest
    steps:
     # - name: Get Code
     #   uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl
          tools: composer:v${{ inputs.composer-version }}
          coverage: none