name: 'Check PHP-CS_Fixer, Language-Sort-Check, Special-Char-Checker, PHP-Unit-Tests and Setup-Process'
on:
  pull_request:
    branches:
      - release_7
#  schedule:
#    - cron: "0 12 * * *"
#  workflow_dispatch:
#permissions:
#  contents: read
#  pull-requests: read

jobs:
  PHP-CS-Fixer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [7.3, 7.4]
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Print event
        run: echo "${{ toJSON(github.event) }}"

      - name: Install PHP
        uses: ./.github/actions/install-php
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Load and Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: PHP CS Fixer
        run: CI/PHP-CS-Fixer/run_check.sh
        env:
          GHRUN: "yes"

  Language-Sort-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: ./.github/actions/install-php
        with:
          php-version: 7.4

      - name: Language Sort Check
        run: CI/sort_langfile_entries.sh check

  Special-Char-Checker:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Special Char Checker
        run: CI/Special-Char-Checker/special-char-checker.sh
        env:
          GHRUN: "yes"

  PHP-Unit-Tests:
    needs: PHP-CS-Fixer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [7.3, 7.4]
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: ./.github/actions/install-php
        with:
          php-version: ${{ matrix.php-versions }}
          composer-version: 2

      - name: Load and Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: PHP Unit Test
        run: CI/PHPUnit/run_tests.sh

  Setup-Tests:
    needs: PHP-Unit-Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: 7.4
    env:
      DB_PASSWORD: root
      DB_DATABASE: ilias
      DB_USER: root
    steps:
      - name: Setup MySql
        run: sudo /etc/init.d/mysql start

      - name: Get Code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: ./.github/actions/install-php
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Load and Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Create ilias directory
        run: mkdir -p /home/runner/work/out

      - name: Run setup
        run: php setup/setup.php install setup/minimal-config.json -y