name: Check the setup process
on:
  push:
    branches:
      - action-test

jobs:
  PHP-Unit-Tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release_7: [7.4]

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.release_7 }}
          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl
          tools: composer:v1
          coverage: none

      - name: Load and Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: PHP Unit Test
        run: CI/PHPUnit/run_tests.sh

  PHP-CS-Fixer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release_7: [7.4]

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.release_7 }}
          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl
          tools: composer:v1
          coverage: none

      - name: Load and Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: PHP CS Fixer
        run: CI/PHP-CS-Fixer/run_check.sh
        env:
          GHRUN: "yes"
          PR_NUMBER: ${{ github.event.pull_request.number }}

  Language-Sort-Check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release_7: [7.4]

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.release_7 }}
          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl
          tools: composer:v1
          coverage: none

      - name: Load and Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Language Sort Check
        run: CI/sort_langfile_entries.sh check
        env:
          GHRUN: "yes"
          PR_NUMBER: ${{ github.event.number }}
          GH_SHA: ${{ github.sha }}

  Special-Char-Checker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release_7: [7.4]

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.release_7 }}
          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl
          tools: composer:v1
          coverage: none

      - name: Load and Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Special Char Checker
        run: CI/Special-Char-Checker/special-char-checker.sh
        env:
          GHRUN: "yes"
          PR_NUMBER: ${{ github.event.pull_request.number }}

  setup-tests:
    needs: [PHP-Unit-Tests, Special-Char-Checker]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release_7: [7.4]
    env:
      DB_PASSWORD: root
      DB_DATABASE: ilias
      DB_USER: root
    steps:
      - name: Setup MySql
        run: sudo /etc/init.d/mysql start

      - name: Get Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.release_7 }}
          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl, mysql
          tools: composer:v1
          coverage: none

      - name: Load and Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Create ilias directory
        run: mkdir -p /home/runner/work/out

      - name: Run setup
        run: php setup/setup.php install setup/minimal-config.json -y