name: Check the setup process
on:
  push:
    branches:
      - action-test

jobs:
  container-test:
    runs-on: ubuntu-latest
    env:
      MARIADB_ROOT_PASSWORD: ilias
      MARIADB_DATABASE: ilias
      MARIADB_USER: ilias
      MARIADB_ROOT_HOST: 127.0.0.1:3306
    services:
      mariadb:
        image: mariadb:10.9
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: ilias
          MARIADB_USER: ilias
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, gd, json, readline, xsl
          tools: composer:v1
          coverage: none
     # - name: Get Composer Cache Directory
     #   id: composer-cache
     #   run: echo "{dir}={$(composer config cache-files-dir)}" >> GITHUB_OUTPUT
     # - uses: actions/cache@v3
     #   with:
     #     path: ${{ steps.composer-cache.outputs.dir }}
     #     key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
     #     restore-keys: |
     #       ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --no-interaction --no-progress
     # - name: PHP Unit Test
      #  run: CI/PHPUnit/run_tests.sh
      - name: Create ilias directory
        run: mkdir out
      - name: Run setup
        run: php setup/setup.php install setup/minimal-config.json -y

